In [2]:
import pandas as pd

In [15]:
url=("https://data.moenv.gov.tw/api/v2/aqx_p_02?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=datacreationdate%20desc&format=CSV")

In [16]:
df=pd.read_csv(url)
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  46.0  2023-11-05 08:00    μg/m3
1   富貴角    新北市   8.0  2023-11-05 08:00    μg/m3
2    麥寮    雲林縣  44.0  2023-11-05 08:00    μg/m3
3    關山    臺東縣   2.0  2023-11-05 08:00    μg/m3
4    馬公    澎湖縣   8.0  2023-11-05 08:00    μg/m3
..  ...    ...   ...               ...      ...
73   土城    新北市  22.0  2023-11-05 08:00    μg/m3
74   新店    新北市   6.0  2023-11-05 08:00    μg/m3
75   萬里    新北市   5.0  2023-11-05 08:00    μg/m3
76   汐止    新北市   7.0  2023-11-05 08:00    μg/m3
77   基隆    基隆市   5.0  2023-11-05 08:00    μg/m3

[78 rows x 5 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   site              78 non-null     object
 1   county            78 non-null     object
 2   pm25              77 non-null     float64
 3   datacreationdate  78 non-null     object
 4   itemunit          78 non-null     object
dtypes: float64(1), object(4)
memory usage: 3.2+ KB

In [18]:
df=df.dropna()
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  46.0  2023-11-05 08:00    μg/m3
1   富貴角    新北市   8.0  2023-11-05 08:00    μg/m3
2    麥寮    雲林縣  44.0  2023-11-05 08:00    μg/m3
3    關山    臺東縣   2.0  2023-11-05 08:00    μg/m3
4    馬公    澎湖縣   8.0  2023-11-05 08:00    μg/m3
..  ...    ...   ...               ...      ...
73   土城    新北市  22.0  2023-11-05 08:00    μg/m3
74   新店    新北市   6.0  2023-11-05 08:00    μg/m3
75   萬里    新北市   5.0  2023-11-05 08:00    μg/m3
76   汐止    新北市   7.0  2023-11-05 08:00    μg/m3
77   基隆    基隆市   5.0  2023-11-05 08:00    μg/m3

[77 rows x 5 columns]

df.sort_values("pm25").iloc[0]['site','pm25'].values

df.sort_values("pm25").iloc[-1]['site','pm25'].values

# 六都平均值

In [19]:
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  46.0  2023-11-05 08:00    μg/m3
1   富貴角    新北市   8.0  2023-11-05 08:00    μg/m3
2    麥寮    雲林縣  44.0  2023-11-05 08:00    μg/m3
3    關山    臺東縣   2.0  2023-11-05 08:00    μg/m3
4    馬公    澎湖縣   8.0  2023-11-05 08:00    μg/m3
..  ...    ...   ...               ...      ...
73   土城    新北市  22.0  2023-11-05 08:00    μg/m3
74   新店    新北市   6.0  2023-11-05 08:00    μg/m3
75   萬里    新北市   5.0  2023-11-05 08:00    μg/m3
76   汐止    新北市   7.0  2023-11-05 08:00    μg/m3
77   基隆    基隆市   5.0  2023-11-05 08:00    μg/m3

[77 rows x 5 columns]

In [20]:
set(df['county'])

{'南投縣',
 '嘉義市',
 '嘉義縣',
 '基隆市',
 '宜蘭縣',
 '屏東縣',
 '彰化縣',
 '新北市',
 '新竹市',
 '新竹縣',
 '桃園市',
 '澎湖縣',
 '臺中市',
 '臺北市',
 '臺南市',
 '臺東縣',
 '花蓮縣',
 '苗栗縣',
 '連江縣',
 '金門縣',
 '雲林縣',
 '高雄市'}

In [21]:
six_countys=['新北市','臺北市','桃園市','臺中市','臺南市','高雄市']
six_countys

['新北市', '臺北市', '桃園市', '臺中市', '臺南市', '高雄市']

In [29]:
df['county']
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  46.0  2023-11-05 08:00    μg/m3
1   富貴角    新北市   8.0  2023-11-05 08:00    μg/m3
2    麥寮    雲林縣  44.0  2023-11-05 08:00    μg/m3
3    關山    臺東縣   2.0  2023-11-05 08:00    μg/m3
4    馬公    澎湖縣   8.0  2023-11-05 08:00    μg/m3
..  ...    ...   ...               ...      ...
73   土城    新北市  22.0  2023-11-05 08:00    μg/m3
74   新店    新北市   6.0  2023-11-05 08:00    μg/m3
75   萬里    新北市   5.0  2023-11-05 08:00    μg/m3
76   汐止    新北市   7.0  2023-11-05 08:00    μg/m3
77   基隆    基隆市   5.0  2023-11-05 08:00    μg/m3

[77 rows x 5 columns]

In [37]:
df.groupby('county').get_group('桃園市')

   site county  pm25  datacreationdate itemunit
11   中壢    桃園市  29.0  2023-11-05 08:00    μg/m3
57   龍潭    桃園市  17.0  2023-11-05 08:00    μg/m3
58   平鎮    桃園市  28.0  2023-11-05 08:00    μg/m3
59   觀音    桃園市  42.0  2023-11-05 08:00    μg/m3
60   大園    桃園市  38.0  2023-11-05 08:00    μg/m3
61   桃園    桃園市  17.0  2023-11-05 08:00    μg/m3

In [31]:
df.groupby('county').get_group('新北市')['pm25'].mean()

11.545454545454545

In [34]:
six_data={}
for county in six_countys:
    print(county)
    print(df.groupby('county').get_group(county)['pm25'].mean())
    six_data[county]=round(df.groupby('county').get_group(county)['pm25'].mean())
    # six_data.append([county,df.groupby('county').get_group(county)['pm25'].mean()])

six_data

新北市
11.545454545454545
臺北市
9.0
桃園市
28.5
臺中市
17.0
臺南市
28.5
高雄市
27.083333333333332

{'新北市': 12, '臺北市': 9, '桃園市': 28, '臺中市': 17, '臺南市': 28, '高雄市': 27}

# 單一縣市的pm2.5數據

## index()要先排除 .set_index(' ')

### 字典格式取值 .to_dict()[' ']

In [46]:
df.groupby('county').get_group('臺北市')[["site","pm25"]].set_index('site').to_dict()['pm25']

{'陽明': 2.0,
 '大同': 14.0,
 '松山': 10.0,
 '古亭': 9.0,
 '萬華': 8.0,
 '中山': 8.0,
 '士林': 12.0}